from enum import Enum, auto

class Category(Enum):
    Drama = "Stories that focus on realistic character development and emotional themes, often dealing with serious life issues."
    Comedy = "Films designed to amuse and entertain, ranging from slapstick and parody to romantic and dark comedies."
    Action = "High-energy movies featuring physical feats, chases, fights, stunts, and large-scale set pieces."
    Thriller = "Tense, suspense-driven films that build anticipation through plot twists, mysteries, or psychological conflict."
    Horror = "Designed to elicit fear or shock, often featuring supernatural elements, monsters, or psychological terror."
    Romance = "Centered on love stories and emotional relationships, from lighthearted meet-cutes to tragic heartbreak."
    Science_Fiction = "Imaginative narratives about futuristic technology, space travel, time travel, or alternate realities."
    Adventure = "Exciting journeys and explorations, often in exotic or dangerous locales, with a focus on heroism and discovery."
    Animation = "Films created frame-by-frame (hand-drawn, stop-motion, or CGI), appealing to all ages with stylized visuals."
    Documentary = "Non-fictional works that explore real events, people, or phenomena, from nature and history to social issues."
    Fantasy = "Stories with magical or supernatural elements, mythical creatures, and invented worlds or systems of magic."
    Crime = "Centered on criminal acts and investigations, depicting gangsters, heists, or police procedural details."
    Mystery = "Plots built around solving puzzles, crimes, or unexplained phenomena—often overlapping with thriller or crime."
    Musical = "Characters express themselves and advance the plot through song and dance numbers woven into the narrative."
    Family = "Wholesome, all-ages entertainment with themes and storytelling accessible to children and parents alike."
    Historical = "Dramatizations set in a specific past era, emphasizing authenticity in setting, costume, and social context."
    Western = "Tales of the American frontier, typically featuring cowboys, outlaws, lawmen, and themes of rugged individualism."
    Biographical = "Dramatized portrayals of real persons’ lives, highlighting key events, achievements, or personal struggles."
    War = "Depictions of armed conflict and its impact on soldiers and civilians, ranging from epic battles to gritty realism."
    Sports = "Stories revolving around athletic competition, underdog triumphs, team dynamics, and personal redemption."
    Noir = "Dark, stylistic crime dramas marked by cynical antiheroes, moral ambiguity, and stark chiaroscuro visuals."
    Superhero = "Adventures of costumed heroes with extraordinary powers, based on comic-book mythology or original concepts."
    Adult_Animation = "Animated films or series aimed at mature audiences, often tackling complex or darker themes."
    Martial_Arts = "Focused on hand-to-hand combat and choreographed fight sequences rooted in Eastern fighting styles."
    Disaster = "Narratives built around large-scale catastrophes—natural or man-made—and human survival efforts."
    Music = "Films centered on musical performances, musicians, or the music industry, where music itself is a central element of the plot."
    Film_Noir = "Dark, cynical movies from the 1940s-50s featuring crime, moral ambiguity, shadowy visuals, and fatalistic themes."